### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by zxiest** [smysnk/gulp-rev-all#130]
I have the code below and getting the `TypeError` above at `revall.manifestFile()`. Any idea why this might be happening?

If I'm not missing something, my code is almost identical to the example given under the manifestFile section in the readme.

```javascript
  revall = new RevAll();

  gulp.src(["assets/**"])
  .pipe(gulp.dest(config.cssOutPath))
  .pipe(revall.revision())
  .pipe(gulp.dest(config.cssOutPath))
  .pipe(revall.manifestFile())
  .pipe(gulp.dest(config.cssOutPath))
````

**Comment by thehindenburg** [comment]
:+1: I have a co-worker who is having the same problem, but it's not everyone on our team...

**Comment by hjbuchanan** [comment]
I was getting a similar error. What version of sass are you running?

**Comment by vitorbaptista** [comment]
I was getting this error and found my mistake. My `rev` rule looked like:

```javascript
gulp.task('rev', ['styles'], () => {
  const revAll = new plugins.revAll();

  return gulp.src(['dist/styles/index.min.css'])
    .pipe(revAll.revision())
    .pipe(gulp.dest('dist'))
    .pipe(revAll.manifestFile())
    .pipe(gulp.dest('dist'));
});
```

The issue was that `dist/styles/index.min.css` didn't exist at that time, so I ended up getting:

```
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at Revisioner.manifestFile (/home/vitor/Projetos/okfn/opentrials/opentrials/node_modules/gulp-rev-all/revisioner.js:98:24)
    at Transform._flush (/home/vitor/Projetos/okfn/opentrials/opentrials/node_modules/gulp-rev-all/index.js:74:34)
    at Transform.<anonymous> (/home/vitor/Projetos/okfn/opentrials/opentrials/node_modules/gulp-rev-all/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at Transform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at Transform.emit (events.js:179:7)
    at finishMaybe (/home/vitor/Projetos/okfn/opentrials/opentrials/node_modules/gulp-rev-all/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (/home/vitor/Projetos/okfn/opentrials/opentrials/node_modules/gulp-rev-all/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
```

Which is very cryptic. The fix was simply making sure the file exists before running `revAll` :+1:

**Comment by york-xtrem** [comment]
I've written debug to see what happens, I agree with @vitorbaptista.

## My html task:

```javascript
    .....
    .pipe($.if('*.html', $.size({
      title: 'html',
      showFiles: true,
      gzip: true
    })))
    .pipe(indexHtmlFilter)
    .pipe($.debug({ title: 'Before rev:' }))
    // .pipe($.rev())
    .pipe(revAll.revision())
    .pipe($.debug({ title: 'After rev:' }))
    .pipe(indexHtmlFilter.restore)
    .pipe($.debug({ title: 'Before revReplace:' }))
    .pipe(revReplace())
    .pipe(gulp.dest(PATHS.dist));
    .....
```

## Result:

```javascript
[20:31:44] Starting 'html'...
[20:31:44] html index.html 2.16 kB (gzipped)
[20:31:44] Before revReplace: dist/index.html
[20:31:44] Before rev: dist/assets/css/main.css
[20:31:44] html styleguide.html 4.69 kB (gzipped)
[20:31:44] Before revReplace: dist/styleguide.html
[20:31:48] Before rev: dist/assets/js/bundle.js
[20:31:48] html all files 6.85 kB (gzipped)
[20:31:48] Before rev: 2 items
[20:31:48] After rev: dist/assets/css/main.9d626f13.css
[20:31:48] After rev: dist/assets/js/bundle.dba5637b.js
[20:31:48] After rev: 2 items
[20:31:48] Before revReplace: dist/assets/css/main.9d626f13.css
[20:31:48] 'html' errored after 3.93 s
[20:31:48] TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1226:5)
    at fmtPath (/Users/York/Downloads/gulpfile/york/node_modules/gulp-rev-replace/index.js:99:24)
    at DestroyableTransform.collectRevs [as _transform] (/Users/York/Downloads/gulpfile/york/node_modules/gulp-rev-replace/index.js:39:18)
    at DestroyableTransform.Transform._read (/Users/York/Downloads/gulpfile/york/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/York/Downloads/gulpfile/york/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/York/Downloads/gulpfile/york/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/Users/York/Downloads/gulpfile/york/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/Users/York/Downloads/gulpfile/york/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at DestroyableTransform.ondata (/Users/York/Downloads/gulpfile/york/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:546:20)

```

**With gulp-rev doesn't happen.**
