### ISSUE TITLE
gulp-rev-all throws error on large video file

### ISSUE THREAD

**Issue by postme** [smysnk/gulp-rev-all#178]
gulp-rev-all throws error on large file (316 Mb MP4 video file)

```
buffer.js:495
    throw new Error('"toString()" failed');
    ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:495:11)
    at Revisioner.processFile (/usr/share/nginx/www.secumail.nl/node_modules/gulp-rev-all/revisioner.js:157:42)
    at Transform._transform (/usr/share/nginx/www.secumail.nl/node_modules/gulp-rev-all/index.js:23:20)
    at Transform._read (/usr/share/nginx/www.secumail.nl/node_modules/gulp-rev-all/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/usr/share/nginx/www.secumail.nl/node_modules/gulp-rev-all/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/share/nginx/www.secumail.nl/node_modules/gulp-rev-all/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/share/nginx/www.secumail.nl/node_modules/gulp-rev-all/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/usr/share/nginx/www.secumail.nl/node_modules/gulp-rev-all/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at emitReadable_ (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (/usr/share/nginx/www.secumail.nl/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/usr/share/nginx/www.secumail.nl/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

**Comment by pioug** [comment]
Should be solved by https://github.com/smysnk/gulp-rev-all/pull/167
