### ISSUE TITLE
writing out manifest file fails gulp4

### ISSUE THREAD

**Issue by eliasmamo** [smysnk/gulp-rev-all#181]
The following task started to fail, though it used to work fine. 
```
function addRevision() {
  return gulp
    .src(['./build/unbundled/**', '!./build/unbundled/bower_components/**/*'])
    .pipe(RevAll.revision({))
    .pipe(gulp.dest('./build/temp'))
    .pipe(RevAll.manifestFile())
    .pipe(gulp.dest('./build/temp'));
}
```
fails with
```
[11:20:01] Error: premature close
    at Pumpify.onclose (/home/ZZZ/main/app/node_modules/end-of-stream/index.js:43:67)
    at emitNone (events.js:106:13)
    at Pumpify.emit (events.js:208:7)
    at Pumpify.Duplexify._destroy (/home/ZZZ/main/app/node_modules/duplexify/index.js:192:8)
    at /home/ZZZ/main/app/node_modules/duplexify/index.js:175:10
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
If i remoe this line RevAll.manifestFile() it works fine.

**Comment by dEEpProjects** [comment]
Upgrading to gulp 4, a similar task of mine started to fail, returning:
```
[16:03:24] Error: Received a non-Vinyl object in `dest()`
    at DestroyableTransform.normalize [as _transform] (/Users/user/Desktop/app/node_modules/vinyl-fs/lib/dest/prepare.js:16:17)
    at DestroyableTransform.Transform._read (/Users/user/Desktop/app/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/user/Desktop/app/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/user/Desktop/app/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/user/Desktop/app/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/Users/user/Desktop/app/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Pumpify.Duplexify._write (/Users/user/Desktop/app/node_modules/duplexify/index.js:212:22)
    at doWrite (/Users/user/Desktop/app/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/user/Desktop/app/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Pumpify.Writable.write (/Users/user/Desktop/app/node_modules/readable-stream/lib/_stream_writable.js:322:11)
```

**Comment by dEEpProjects** [comment]
It seems related to the use of the deprecated gulp-util. 
The #183 PR needs to be merged (issue related #182).

**Comment by littledu** [comment]
I am experiencing the same problem

**Comment by littledu** [comment]
https://github.com/gulpjs/vinyl-fs/issues/288
vinyl-fs 3 is a major, breaking version. Plugins will need to be updated to use a version of Vinyl that supports isVinyl()

**Comment by pioug** [comment]
I got maintainer permissions and published a new version https://www.npmjs.com/package/gulp-rev-all/v/0.9.8 🙏 It should work better with Gulp 4 now!
