### ISSUE TITLE
npm test triggers ReferenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by dpilafian** [smysnk/gulp-rev-all#202]
Steps:
```bash
$ git clone https://github.com/smysnk/gulp-rev-all.git
$ cd gulp-rev-all
$ npm test
```

Result:
```
> gulp-rev-all@1.0.0 test /Users/dem.pilafian/Heap/projects/gulp-rev-all
> mocha test.js

internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/natives/index.js:137:5)
    at require (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/natives/index.js:137:5)
    at require (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/vinyl-fs/lib/src/getContents/index.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/vinyl-fs/lib/src/index.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/vinyl-fs/index.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/gulp/index.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dem.pilafian/Heap/projects/gulp-rev-all/test.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/dem.pilafian/Heap/projects/gulp-rev-all/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! Test failed.  See above for more details.
```

Environment:
```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
$ node --version
v10.15.3
$ npm --version
6.4.1
```

**Comment by pioug** [comment]
Fixed in https://github.com/smysnk/gulp-rev-all/pull/204
