### ISSUE TITLE
gulp-rev-all 0.8 fails if glob is not installed explicitly

### ISSUE THREAD

**Issue by Achrome** [smysnk/gulp-rev-all#77]
Recently updated `gulp-rev-all` to 0.8.7 from 0.7.6

It failed my deploy task with the following error

```javascript
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/the-van-and-man/node_modules/gulp-rev-all/tool.js:4:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

However, once I explicitly installed `glob`, it worked fine. It would seem that `glob` should be a dependency instead of a `devDependency`.

Sending a PR to correct this.

**Comment by smysnk** [comment]
Thanks!
